### PR TITLE
WIP: Add list of mainnet tokens

### LINKED ISSUE #45: Build token list for mainnet
The app needs a list of tokens which can be used on mainnet. This is limited to those indexed by the [sablier subgraph](https://github.com/sablierhq/sablier-subgraph)

### PR DESCRIPTION
**Pull request by TomAFrench**
- [x] Get full list of desired mainnet tokens
- [x] add icon for each token
- [x] double check number of decimals for each token

closes #45

### CODE REVIEW

**Comment by TomAFrench** [comment]
@PaulRBerg Can you chuck the list of token icons you use in the assets folder for me please?

**Comment by TomAFrench** [comment]
I've added the addresses/icons for popular tokens from the Sablier subgraph. I've skipped the personal tokens to keep the list short (sorry no PAUL tokens).

This list can only be seen on mainnet.

Screenshot_2020-06-11_16-21-42

@PaulRBerg, unless there's any extra tokens you want to add this should be ready to merge.

**Comment by PaulRBerg** [comment]
Hah, I'm fine without the $PAUL token listed (for now).

The only change that I did was to reorder the tokens like this:

1. Ether
2. Vanilla stablecoins
3. Interest-bearing stablecoins
4. All others ERC20s

And remove a few tokens:

+ BAT
+ KNC
+ REP
+ SNX

The vast majority of volume of Sablier v1 was driven by stablecoins and Ether. Less tokens = no tyranny of the choice for users.

**Comment by TomAFrench** [comment]
Sure thing. That works for me.

**Pull request merged**
