### PR TITLE
Implement expandable stream table rows

### LINKED ISSUE #43: Tap row item and open the Sablier Interface page
It'd be nice to redirect the user to the Sablier Interface when they tap a row in the "Manage Created Streams" table.

There's no way we will ever fit as much rich data in the Safe App as there can be displayed on the canonical web app.

### PR DESCRIPTION
**Pull request by TomAFrench**
This PR implements behaviour allowing users to click on a stream in the table to display extra information.

Screenshot_2020-06-10_19-33-15

At this point it's just a matter of choosing how to lay out information in the expansion drawer.

At the minute I'm planning:
- [x] Add etherscan link to recipient
- [x] ~~Add etherscan link to stream creation transaction~~
- [x] ~~Add etherscan link to stream cancellation transaction~~
- [X] Add links to [app.sablier.finance](https://app.sablier.finance)
- [x] Add display on what value of the stream is currently owned by sender/recipient

@PaulRBerg If there's any information/actions I've forgotten that you'd like to add. Please feel free to add to the list.

fixes #43

### CODE REVIEW

**Comment by PaulRBerg** [comment]
While testing this, I encountered this bug:

Capture d’écran 2020-06-11 à 21 47 26

What I did:

1. Go to dashboard page
2. Click the down arrow to expand the cancelled stream
3. Scroll to the right of the screen to see all details
4. Click the up arrow to shrink the cancelled stream

**Comment by PaulRBerg** [comment]
## UI

- [ ] Obviously, the text layout should be enhanced. Links should be clickable, or better, they should be transformed into buttons (e.g. "Etherscan Link")

## Source Code
- [x] Memoize all non-memoized variables in `GnoTable`
- [x] Callbackify all non-callbackified functions in `GnoTable`

There are a few other minor things like `stableSort` returning an `any` type, but they're not terribly blad.

**Comment by TomAFrench** [comment]
Just as a quick update on where we are currently:

The expansion panel now looks like this.
Screenshot_2020-06-12_15-43-33

- [ ] changing "Stream Progress" to display "starting in x days, y hours, z minutes" for streams yet to start.
- [ ] adding the standard "copy to clipboard" and "open on etherscan" buttons to the recipient line
- [ ] bolding the field names
- [ ] Center the buttons on right hand side.

**Comment by TomAFrench** [comment]
> While testing, I encountered this bug:
> [snip]

Yeah, there was an issue when the stream went back to the no-expanded-rows state where it tried to display a null stream. This has been sorted now in ace5386

**Comment by PaulRBerg** [comment]
> All the values in the expansion panel are recalculated every second so users can watch the balances change in real time (no external calls so this frequency is fine).

Ah, fantastic. JavaScript timers have done wonders to the Internet.

> Center the buttons on right hand side.

You mean stacking "View Stream" and "Cancel" vertically?

> Add a "copy recipient link" button

Yeah, I think this is the only important thing left to do.

**Comment by TomAFrench** [comment]
> You mean stacking "View Stream" and "Cancel" vertically?

I mean, I'd like to center them vertically and add some padding around each button.

**Pull request merged**
